server:
  port: 8877
#spring:
#  rabbitmq:
#    host: 192.168.159.8
#    port: 5672
#    virtual-host: tulingmall
#    username: smlz
#    password: smlz
#    publisher-confirms: true #如果对异步消息需要回调必须设置为true
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  secret: mall-portal-secret #JWT加解密使用的密钥
#  expiration: 604800 #JWT的超期限时间(60*60*24)
#  tokenHead: bearer #JWT负载中拿到开头

# 自定义redis键值
#redis:
#  key:
#    prefix:
#      authCode: "portal:authCode:"
#      orderId: "portal:orderId:"
#    expire:
#      authCode: 90 # 验证码超期时间



