spring:
  datasource:
    dynamic:
      primary: user
      # 未匹配到数据源时，true抛异常，false使用默认数据源
      strict: false
      datasource:
        user:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_user?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        goods:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_goods?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        promotion:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_promotion?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        normal:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_normal?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        order:
          url: jdbc:mysql://192.168.65.223:3306/tl_mall_order?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
#    url: jdbc:mysql://192.168.65.71:3306/tl_mall_normal?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: tlmall
#    password: tlmall123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
feign:
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.tuling.tulingmall.portal.feignapi.interceptor.HeaderInterceptor
        readTimeout: 3000
        connectTimeout: 3000
logging:
  level:
    root: info
server:
  port: 8887
promotion:
  demo:
    allowLocalCache: true
    allowRemoteCache: true

