server:
  port: 8085
spring:
  datasource:
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    dynamic:
      primary: user
      # 未匹配到数据源时，true抛异常，false使用默认数据源
      strict: false
      datasource:
        user:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_user?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        goods:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_goods?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        promotion:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_promotion?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        normal:
          url: jdbc:mysql://192.168.65.71:3306/tl_mall_normal?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
        order:
          url: jdbc:mysql://192.168.65.223:3306/tl_mall_order?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: tlmall
          password: tlmall123
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: tl.es.com:9300
#      cluster-name: elasticsearch
  application:
    name: tulingmall-search
  cloud:
    nacos:
      discovery:
        server-addr: tl.nacos.com:8848
  data:
    elasticsearch:
      rest:
        #uris: 192.168.21.130:9300,192.168.21.131:9300,192.168.21.132:9300
        uris: tl.es.com:9300

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml




