server:
  port: 8856
spring:
  application:
      name: tulingmall-canal
  data:
    elasticsearch:
      rest:
        uris: 192.168.65.219:9300,192.168.65.110:9300,192.168.65.113:9300
      client:
        reactive:
          password: es
          username: es
canal:
  server:
    ip: 192.168.65.201
    port: 8888
  product:
    destination: product
    indexName: product_db
    batchSize: 1000
  promotion:
    destination: promotion
    batchSize: 1000
  seckill:
    destination: seckill
    batchSize: 1000

#rocketmq配置
#rocketmq:
#  name-server: 192.168.65.164:9876,192.168.65.194:9876,192.168.65.161:9876,192.168.65.148:9876,192.168.65.224:9876,192.168.65.215:9876, #连接超时时间
#  producer:
#    send-message-timeout: 30000 #发送消息超时时间
#  canal:
#    topic: productDetailChange
#    group: cache-sync